theme = "ayu_dark"

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"